### ISSUE TITLE
Compatibility with ffmpeg 4.4

### ISSUE THREAD

**Issue by peet1993** [zmwangx/rust-ffmpeg#61]
The wrapper currently does not compile with ffmpeg 4.4, which is currently packaged in at least Arch and Manjaro.
Are there plans to update it?

cargo build output:
```Compiling ffmpeg-next v4.4.0-dev (/home/peet/GitRepos/rust-ffmpeg)
error[E0004]: non-exhaustive patterns: `AV_PIX_FMT_X2RGB10LE` and `AV_PIX_FMT_X2RGB10BE` not covered
    --> src/util/format/pixel.rs:407:15
     |
407  |         match value {
     |               ^^^^^ patterns `AV_PIX_FMT_X2RGB10LE` and `AV_PIX_FMT_X2RGB10BE` not covered
     | 
    ::: /home/peet/GitRepos/rust-ffmpeg/target/debug/build/ffmpeg-sys-next-07c0e71615a1ac1d/out/bindings.rs:5836:5
     |
5836 |     AV_PIX_FMT_X2RGB10LE = 196,
     |     -------------------- not covered
5837 |     AV_PIX_FMT_X2RGB10BE = 197,
     |     -------------------- not covered
     |
     = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
     = note: the matched value is of type `sys::AVPixelFormat`

error[E0004]: non-exhaustive patterns: `AV_FRAME_DATA_SEI_UNREGISTERED` and `AV_FRAME_DATA_FILM_GRAIN_PARAMS` not covered
    --> src/util/frame/side_data.rs:60:15
     |
60   |         match value {
     |               ^^^^^ patterns `AV_FRAME_DATA_SEI_UNREGISTERED` and `AV_FRAME_DATA_FILM_GRAIN_PARAMS` not covered
     | 
    ::: /home/peet/GitRepos/rust-ffmpeg/target/debug/build/ffmpeg-sys-next-07c0e71615a1ac1d/out/bindings.rs:6396:5
     |
6396 |     AV_FRAME_DATA_SEI_UNREGISTERED = 22,
     |     ------------------------------ not covered
6397 |     AV_FRAME_DATA_FILM_GRAIN_PARAMS = 23,
     |     ------------------------------- not covered
     |
     = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
     = note: the matched value is of type `sys::AVFrameSideDataType`

error[E0004]: non-exhaustive patterns: `AV_CODEC_ID_PGX`, `AV_CODEC_ID_AVS3`, `AV_CODEC_ID_MSP2` and 11 more not covered
   --> src/codec/id.rs:586:15
    |
586 |         match value {
    |               ^^^^^ patterns `AV_CODEC_ID_PGX`, `AV_CODEC_ID_AVS3`, `AV_CODEC_ID_MSP2` and 11 more not covered
    |
    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
    = note: the matched value is of type `sys::AVCodecID`

error[E0004]: non-exhaustive patterns: `AV_PKT_DATA_S12M_TIMECODE` not covered
    --> src/codec/packet/side_data.rs:55:15
     |
55   |         match value {
     |               ^^^^^ pattern `AV_PKT_DATA_S12M_TIMECODE` not covered
     | 
    ::: /home/peet/GitRepos/rust-ffmpeg/target/debug/build/ffmpeg-sys-next-07c0e71615a1ac1d/out/bindings.rs:8963:5
     |
8963 |     AV_PKT_DATA_S12M_TIMECODE = 30,
     |     ------------------------- not covered
     |
     = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
     = note: the matched value is of type `sys::AVPacketSideDataType`

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0004`.
error: could not compile `ffmpeg-next`
```

ffmpeg -version
```
ffmpeg version n4.4 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.2.0 (GCC)
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
```

**Comment by Polochon-street** [comment]
There's a PR here https://github.com/zmwangx/rust-ffmpeg/pull/60, I think it's waiting for approval by @zmwangx :)

**Comment by peet1993** [comment]
You are right, i overlooked that!
