### ISSUE TITLE
Can't build on macos 13.4: ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by sujaymansingh** [zmwangx/rust-ffmpeg#158]
I'm on MacOS 13.4 (22F66)

I'm trying to use ffmpeg-next to build a video from a series of image files.

I can get `ffmpeg-next = { version = "6.0.0", features = ["build"] }` to build, but then I don't have any h264 capabilities. (Most examples, and the libraries that sit on top of this, e.g. video-rs, use h264)

If I add `ffmpeg-next = { version = "6.0.0", features = ["build", "codec", "build-license-gpl", "build-lib-x264"] }` I get the following when I build:

```
...
  = note: ld: warning: could not create compact unwind for _ff_rl_init_vlc: stack subq instruction is too different from dwarf stack size
          Undefined symbols for architecture x86_64:
            "_x264_param_cleanup", referenced from:
                _X264_close in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_encoder_close", referenced from:
                _X264_close in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_picture_init", referenced from:
                _X264_frame in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_encoder_reconfig", referenced from:
                _X264_frame in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_encoder_encode", referenced from:
                _X264_frame in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_param_default", referenced from:
                _X264_init in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_param_apply_fastfirstpass", referenced from:
                _X264_init in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_levels", referenced from:
                _X264_init in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_encoder_open_164", referenced from:
                _X264_init in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_param_default_preset", referenced from:
                _X264_init in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_param_apply_profile", referenced from:
                _X264_init in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_param_parse", referenced from:
                _X264_init in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
                _parse_opts in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_encoder_delayed_frames", referenced from:
                _X264_frame in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_encoder_headers", referenced from:
                _X264_init in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
            "_x264_encoder_maximum_delayed_frames", referenced from:
                _X264_init in libffmpeg_sys_next-1911200132984294.rlib(libx264.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This looks like I have something pretty fundamental missing, but I am not sure where to look.
(I have ffmpeg 6 installed via homebrew)

Anyone have any ideas or pointers?

**Comment by dashuai009** [comment]
I have encountered the same problem, have you solved it

**Comment by dashuai009** [comment]
I have found two solutions.

1. Add `extern crate ffmpeg_next;` at the top of your binary.

    https://github.com/huggingface/candle?tab=readme-ov-file#missing-symbols-when-compiling-with-the-mkl-feature

**Or** add such `.cargo/config.toml`
```
[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]
```
2. Add pkg-config to your build.rs
```
extern crate pkg_config;
fn main() {
    let mut config = pkg_config::Config::new();
    config.statik(true).probe("x264").unwrap();

    config.statik(true).probe("dav1d").unwrap();
    // config.statik(true).probe("aom").unwrap();
    // config.statik(true).probe("opencore-amrwb").unwrap();
    //
    // config.statik(true).probe("snappy").unwrap(); 
    config.statik(true).probe("x265").unwrap();
    config.statik(true).probe("vpx").unwrap();
}
```

This will work on macos.

**Comment by darmie** [comment]
@dashuai009 I could not get this to work on MacOS Sonoma M1 Pro.   

> I have found two solutions.
> 
> 1. Add `extern crate ffmpeg_next;` at the top of your binary.
>    https://github.com/huggingface/candle?tab=readme-ov-file#missing-symbols-when-compiling-with-the-mkl-feature
> 
> **Or** add such `.cargo/config.toml`
> 
> ```
> [target.x86_64-apple-darwin]
> rustflags = [
>     "-C", "link-arg=-undefined",
>     "-C", "link-arg=dynamic_lookup",
> ]
> 
> [target.aarch64-apple-darwin]
> rustflags = [
>     "-C", "link-arg=-undefined",
>     "-C", "link-arg=dynamic_lookup",
> ]
> ```
> 
> 2. Add pkg-config to your build.rs
> 
> ```
> extern crate pkg_config;
> fn main() {
>     let mut config = pkg_config::Config::new();
>     config.statik(true).probe("x264").unwrap();
> 
>     config.statik(true).probe("dav1d").unwrap();
>     // config.statik(true).probe("aom").unwrap();
>     // config.statik(true).probe("opencore-amrwb").unwrap();
>     //
>     // config.statik(true).probe("snappy").unwrap(); 
>     config.statik(true).probe("x265").unwrap();
>     config.statik(true).probe("vpx").unwrap();
> }
> ```
> 
> This will work on macos.



> I have found two solutions.
> 
> 1. Add `extern crate ffmpeg_next;` at the top of your binary.
>    https://github.com/huggingface/candle?tab=readme-ov-file#missing-symbols-when-compiling-with-the-mkl-feature
> 
> **Or** add such `.cargo/config.toml`
> 
> ```
> [target.x86_64-apple-darwin]
> rustflags = [
>     "-C", "link-arg=-undefined",
>     "-C", "link-arg=dynamic_lookup",
> ]
> 
> [target.aarch64-apple-darwin]
> rustflags = [
>     "-C", "link-arg=-undefined",
>     "-C", "link-arg=dynamic_lookup",
> ]
> ```
> 
> 2. Add pkg-config to your build.rs
> 
> ```
> extern crate pkg_config;
> fn main() {
>     let mut config = pkg_config::Config::new();
>     config.statik(true).probe("x264").unwrap();
> 
>     config.statik(true).probe("dav1d").unwrap();
>     // config.statik(true).probe("aom").unwrap();
>     // config.statik(true).probe("opencore-amrwb").unwrap();
>     //
>     // config.statik(true).probe("snappy").unwrap(); 
>     config.statik(true).probe("x265").unwrap();
>     config.statik(true).probe("vpx").unwrap();
> }
> ```
> 
> This will work on macos.

**Comment by darmie** [comment]
Thanks I'll try these.
